/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as RegisterImport } from './routes/Register'
import { Route as PerfilImport } from './routes/Perfil'
import { Route as NotificationsImport } from './routes/Notifications'
import { Route as MedicalImport } from './routes/Medical'
import { Route as LoginImport } from './routes/Login'
import { Route as HomePageImport } from './routes/HomePage'
import { Route as DisasterImport } from './routes/Disaster'
import { Route as DetailsImport } from './routes/Details'
import { Route as CreateDonationImport } from './routes/CreateDonation'
import { Route as CommunityImport } from './routes/Community'
import { Route as CharityImport } from './routes/Charity'
import { Route as AnimalsImport } from './routes/Animals'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/Register',
  path: '/Register',
  getParentRoute: () => rootRoute,
} as any)

const PerfilRoute = PerfilImport.update({
  id: '/Perfil',
  path: '/Perfil',
  getParentRoute: () => rootRoute,
} as any)

const NotificationsRoute = NotificationsImport.update({
  id: '/Notifications',
  path: '/Notifications',
  getParentRoute: () => rootRoute,
} as any)

const MedicalRoute = MedicalImport.update({
  id: '/Medical',
  path: '/Medical',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any)

const HomePageRoute = HomePageImport.update({
  id: '/HomePage',
  path: '/HomePage',
  getParentRoute: () => rootRoute,
} as any)

const DisasterRoute = DisasterImport.update({
  id: '/Disaster',
  path: '/Disaster',
  getParentRoute: () => rootRoute,
} as any)

const DetailsRoute = DetailsImport.update({
  id: '/Details',
  path: '/Details',
  getParentRoute: () => rootRoute,
} as any)

const CreateDonationRoute = CreateDonationImport.update({
  id: '/CreateDonation',
  path: '/CreateDonation',
  getParentRoute: () => rootRoute,
} as any)

const CommunityRoute = CommunityImport.update({
  id: '/Community',
  path: '/Community',
  getParentRoute: () => rootRoute,
} as any)

const CharityRoute = CharityImport.update({
  id: '/Charity',
  path: '/Charity',
  getParentRoute: () => rootRoute,
} as any)

const AnimalsRoute = AnimalsImport.update({
  id: '/Animals',
  path: '/Animals',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Animals': {
      id: '/Animals'
      path: '/Animals'
      fullPath: '/Animals'
      preLoaderRoute: typeof AnimalsImport
      parentRoute: typeof rootRoute
    }
    '/Charity': {
      id: '/Charity'
      path: '/Charity'
      fullPath: '/Charity'
      preLoaderRoute: typeof CharityImport
      parentRoute: typeof rootRoute
    }
    '/Community': {
      id: '/Community'
      path: '/Community'
      fullPath: '/Community'
      preLoaderRoute: typeof CommunityImport
      parentRoute: typeof rootRoute
    }
    '/CreateDonation': {
      id: '/CreateDonation'
      path: '/CreateDonation'
      fullPath: '/CreateDonation'
      preLoaderRoute: typeof CreateDonationImport
      parentRoute: typeof rootRoute
    }
    '/Details': {
      id: '/Details'
      path: '/Details'
      fullPath: '/Details'
      preLoaderRoute: typeof DetailsImport
      parentRoute: typeof rootRoute
    }
    '/Disaster': {
      id: '/Disaster'
      path: '/Disaster'
      fullPath: '/Disaster'
      preLoaderRoute: typeof DisasterImport
      parentRoute: typeof rootRoute
    }
    '/HomePage': {
      id: '/HomePage'
      path: '/HomePage'
      fullPath: '/HomePage'
      preLoaderRoute: typeof HomePageImport
      parentRoute: typeof rootRoute
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/Medical': {
      id: '/Medical'
      path: '/Medical'
      fullPath: '/Medical'
      preLoaderRoute: typeof MedicalImport
      parentRoute: typeof rootRoute
    }
    '/Notifications': {
      id: '/Notifications'
      path: '/Notifications'
      fullPath: '/Notifications'
      preLoaderRoute: typeof NotificationsImport
      parentRoute: typeof rootRoute
    }
    '/Perfil': {
      id: '/Perfil'
      path: '/Perfil'
      fullPath: '/Perfil'
      preLoaderRoute: typeof PerfilImport
      parentRoute: typeof rootRoute
    }
    '/Register': {
      id: '/Register'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Animals': typeof AnimalsRoute
  '/Charity': typeof CharityRoute
  '/Community': typeof CommunityRoute
  '/CreateDonation': typeof CreateDonationRoute
  '/Details': typeof DetailsRoute
  '/Disaster': typeof DisasterRoute
  '/HomePage': typeof HomePageRoute
  '/Login': typeof LoginRoute
  '/Medical': typeof MedicalRoute
  '/Notifications': typeof NotificationsRoute
  '/Perfil': typeof PerfilRoute
  '/Register': typeof RegisterRoute
  '/about': typeof AboutRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Animals': typeof AnimalsRoute
  '/Charity': typeof CharityRoute
  '/Community': typeof CommunityRoute
  '/CreateDonation': typeof CreateDonationRoute
  '/Details': typeof DetailsRoute
  '/Disaster': typeof DisasterRoute
  '/HomePage': typeof HomePageRoute
  '/Login': typeof LoginRoute
  '/Medical': typeof MedicalRoute
  '/Notifications': typeof NotificationsRoute
  '/Perfil': typeof PerfilRoute
  '/Register': typeof RegisterRoute
  '/about': typeof AboutRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Animals': typeof AnimalsRoute
  '/Charity': typeof CharityRoute
  '/Community': typeof CommunityRoute
  '/CreateDonation': typeof CreateDonationRoute
  '/Details': typeof DetailsRoute
  '/Disaster': typeof DisasterRoute
  '/HomePage': typeof HomePageRoute
  '/Login': typeof LoginRoute
  '/Medical': typeof MedicalRoute
  '/Notifications': typeof NotificationsRoute
  '/Perfil': typeof PerfilRoute
  '/Register': typeof RegisterRoute
  '/about': typeof AboutRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Animals'
    | '/Charity'
    | '/Community'
    | '/CreateDonation'
    | '/Details'
    | '/Disaster'
    | '/HomePage'
    | '/Login'
    | '/Medical'
    | '/Notifications'
    | '/Perfil'
    | '/Register'
    | '/about'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Animals'
    | '/Charity'
    | '/Community'
    | '/CreateDonation'
    | '/Details'
    | '/Disaster'
    | '/HomePage'
    | '/Login'
    | '/Medical'
    | '/Notifications'
    | '/Perfil'
    | '/Register'
    | '/about'
  id:
    | '__root__'
    | '/'
    | '/Animals'
    | '/Charity'
    | '/Community'
    | '/CreateDonation'
    | '/Details'
    | '/Disaster'
    | '/HomePage'
    | '/Login'
    | '/Medical'
    | '/Notifications'
    | '/Perfil'
    | '/Register'
    | '/about'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimalsRoute: typeof AnimalsRoute
  CharityRoute: typeof CharityRoute
  CommunityRoute: typeof CommunityRoute
  CreateDonationRoute: typeof CreateDonationRoute
  DetailsRoute: typeof DetailsRoute
  DisasterRoute: typeof DisasterRoute
  HomePageRoute: typeof HomePageRoute
  LoginRoute: typeof LoginRoute
  MedicalRoute: typeof MedicalRoute
  NotificationsRoute: typeof NotificationsRoute
  PerfilRoute: typeof PerfilRoute
  RegisterRoute: typeof RegisterRoute
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimalsRoute: AnimalsRoute,
  CharityRoute: CharityRoute,
  CommunityRoute: CommunityRoute,
  CreateDonationRoute: CreateDonationRoute,
  DetailsRoute: DetailsRoute,
  DisasterRoute: DisasterRoute,
  HomePageRoute: HomePageRoute,
  LoginRoute: LoginRoute,
  MedicalRoute: MedicalRoute,
  NotificationsRoute: NotificationsRoute,
  PerfilRoute: PerfilRoute,
  RegisterRoute: RegisterRoute,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Animals",
        "/Charity",
        "/Community",
        "/CreateDonation",
        "/Details",
        "/Disaster",
        "/HomePage",
        "/Login",
        "/Medical",
        "/Notifications",
        "/Perfil",
        "/Register",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Animals": {
      "filePath": "Animals.tsx"
    },
    "/Charity": {
      "filePath": "Charity.tsx"
    },
    "/Community": {
      "filePath": "Community.tsx"
    },
    "/CreateDonation": {
      "filePath": "CreateDonation.tsx"
    },
    "/Details": {
      "filePath": "Details.tsx"
    },
    "/Disaster": {
      "filePath": "Disaster.tsx"
    },
    "/HomePage": {
      "filePath": "HomePage.tsx"
    },
    "/Login": {
      "filePath": "Login.tsx"
    },
    "/Medical": {
      "filePath": "Medical.tsx"
    },
    "/Notifications": {
      "filePath": "Notifications.tsx"
    },
    "/Perfil": {
      "filePath": "Perfil.tsx"
    },
    "/Register": {
      "filePath": "Register.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
